refactor: throw error if sonar not ok

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,29 +42,23 @@ jobs:
       run: |
         status=$(curl -sS -u ${{ secrets.SONAR_TOKEN }}: \
           "https://sonarcloud.io/api/qualitygates/project_status?projectKey=heutelbeck_sapl-nodejs" | jq -r '.projectStatus.status')
-        echo "Sonar Quality Gate Status: $status"
-    - name: set output
-      id: set-output
-      run: echo "sonar_status_output=$status" >> $GITHUB_OUTPUT
+        if [ "$status" != "OK" ]; then
+          echo "Quality gate failed: $status"
+          exit 1  # Bricht den Job mit einem Fehlercode ab
+        fi
+        echo "SONAR_STATUS=$status" >> $GITHUB_ENV
     - name: Print Quality Gate Status
       run: echo $SONAR_STATUS
+
   publish-npm:
     needs: build
     runs-on: ubuntu-latest
-    env:
-      SONAR_STATUS: "${{ needs.build.outputs.sonar_status_output }}"
-      SONAR_STATUS2: "${{ needs.build.set-output.outputs.sonar_status_output }}"
-    # if: needs.build.outputs.SONAR_STATUS_OUTPUT == 'OK'
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
           node-version: 20.x
           registry-url: https://registry.npmjs.org/
-      - name: Print Quality Gate Status
-        run: echo $SONAR_STATUS
-      - name: Print Quality Gate Status 2
-        run: echo $SONAR_STATUS2
       # - run: npm ci
       # - run: npm run build --if-present
       # - run: npm publish --access public
